name: rijksmuseum_app
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  dio: ^5.4.0
  envied: ^0.5.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  photo_view: ^0.14.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.3.3
dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  riverpod_lint: ^2.3.7
  total_lints: ^3.2.0

flutter:
  uses-material-design: true